# Generated by Django 4.2.2 on 2023-11-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Module', '0004_product_image_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(db_index=True, default='url_title', max_length=300, verbose_name='نام برند در url'),
            preserve_default=False,
        ),
    ]
