# Generated by Django 4.2.2 on 2023-11-24 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Module', '0006_productvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/product_galleries', verbose_name='تصویر')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_Module.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
    ]
