# Generated by Django 4.2.2 on 2023-11-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_Module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='count',
            field=models.IntegerField(default=0, verbose_name='تعداد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='final_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت نهایی تکی محصول'),
        ),
    ]
