# Generated by Django 4.2.2 on 2023-09-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=300, verbose_name='نام سایت')),
                ('site_url', models.CharField(max_length=300, verbose_name='دامنه سایت')),
                ('addres', models.CharField(blank=True, max_length=300, null=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=300, null=True, verbose_name='تلفن')),
                ('fax', models.CharField(blank=True, max_length=300, null=True, verbose_name='فکس')),
                ('email', models.CharField(max_length=300, verbose_name='ایمیل')),
                ('about_us_text', models.TextField(verbose_name='متن درباره ما')),
                ('copyright_text', models.TextField(verbose_name='متن کپی رایت')),
                ('site_logo', models.ImageField(upload_to='images/site_setting', verbose_name='تصویر')),
                ('is_main_setting', models.BooleanField(verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
