# Generated by Django 4.2.2 on 2023-09-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیرفعال'),
        ),
    ]
