# Generated by Django 4.2.2 on 2023-11-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Module', '0005_sitebanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitebanner',
            options={'verbose_name': 'بنر تبلیغاتی', 'verbose_name_plural': 'بنرهای تبلیغاتی'},
        ),
    ]
